let translations = {}

translations['en'] = {}
translations['nl'] = {}
translations['de'] = {}
translations['sv'] = {}
translations['hin'] = {}

translations['en']['close'] = "Close"
translations['en']['cancel'] = "Cancel"
translations['en']['refresh'] = "Refresh"
translations['en']['trashItem'] = "Trash"
translations['en']['moveItem'] = "Move"
translations['en']['myCloud'] = "My Cloud"
translations['en']['loginTitle'] = "Sign in"
translations['en']['registerTitle'] = "Create an account"
translations['en']['or'] = "or"
translations['en']['loginButton'] = "Sign in"
translations['en']['registerButton'] = "Create account"
translations['en']['registerLink'] = "Create an account (First 10 GB free)"
translations['en']['loginLink'] = "Sign in"
translations['en']['passwordRepeatPlaceholder'] = "Repeat password"
translations['en']['emailPlaceholder'] = "Email address"
translations['en']['passwordPlaceholder'] = "Password"
translations['en']['2faPlaceholder'] = "2FA code (leave empty if disabled)"
translations['en']['loginInvalidInputs'] = "Invalid email address and password"
translations['en']['alertOkButton'] = "OK"
translations['en']['loginWrongCredentials'] = "Wrong email, password or 2FA code"
translations['en']['apiRequestError'] = "Request error, please try again later"
translations['en']['registerInvalidFields'] = "Invalid form fields"
translations['en']['registerPasswordAtLeast10Chars'] = "Your password needs to be at least 10 characters long"
translations['en']['registerPasswordsDoNotMatch'] = "Passwords do not match"
translations['en']['registerInvalidEmail'] = "Invalid email address"
translations['en']['registerEmailAlreadyRegistered'] = "This email address is already registered"
translations['en']['registerCouldNotSendEmail'] = "OK"
translations['en']['alertOkButton'] = "We could not send an email at this time, please try again later"
translations['en']['registerSuccess'] = "Account created, please confirm your email address by clicking the link we've sent to you"
translations['en']['registerInvalidInputs'] = "Invalid email address, password and confirm password"
translations['en']['sharedWithMe'] = "Shared with me"
translations['en']['currentlySharing'] = "Currently sharing"
translations['en']['settings'] = "Settings"
translations['en']['encryption'] = "Encryption"
translations['en']['help'] = "Help"
translations['en']['trash'] = "Trash"
translations['en']['userStorageUsageMenuText'] = "__PERCENTAGE__% of __MAX__ used"
translations['en']['goProBadge'] = "Go Pro"
translations['en']['unknownDeviceError'] = "An unknown error occured on your device, try restarting the app or contact our support for help"
translations['en']['uploadInvalidFileSize'] = "__NAME__ has an invalid file size"
translations['en']['fileUploadFileAlreadyExists'] = "__NAME__ already exists in this folder"
translations['en']['fileUploadStarted'] = "__NAME__ upload started"
translations['en']['fileUploadCouldNotReadFile'] = "Could not read __NAME__, cancelling upload"
translations['en']['couldNotImportKeys'] = "Could not import your keypair, please try again or contact support"
translations['en']['fileUploadFailed'] = "Could not upload __NAME__, check your internet connection or contact support"
translations['en']['fileUploadDone'] = "__NAME__ uploaded successfully"
translations['en']['fileUploadInvalidFileName'] = "__NAME__ has an invalid name"
translations['en']['fileDownloadAlreadyDownloadingFile'] = "__NAME__ is already being downloaded"
translations['en']['fabUploadFiles'] = "Upload files"
translations['en']['fabCreateFolder'] = "Create folder"
translations['en']['couldNotGetDownloadDir'] = "Could not get download directory, please restart your app/phone or contact support"
translations['en']['fileDownloadStarted'] = "__NAME__ download started"
translations['en']['fileDownloadError'] = "__NAME__ download failed"
translations['en']['downloadItem'] = "Download"
translations['en']['moveItem'] = "Move"
translations['en']['renameItem'] = "Rename"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"

translations['nl']['close'] = "Sluit"
translations['nl']['cancel'] = "Annuleer"
translations['nl']['refresh'] = "Ververs"
translations['nl']['trashItem'] = "Prullenbak"
translations['nl']['moveItem'] = "Verplaats"
translations['nl']['myCloud'] = "Mijn Cloud"
translations['nl']['loginTitle'] = "Log in"
translations['nl']['registerTitle'] = "Maak een account"
translations['nl']['or'] = "of"
translations['nl']['loginButton'] = "Log in"
translations['nl']['registerButton'] = "Maak account"
translations['nl']['registerLink'] = "Maak een account (Eerste 10 GB gratis)"
translations['nl']['loginLink'] = "Log in"
translations['nl']['passwordRepeatPlaceholder'] = "Herhaal wachtwoord"
translations['nl']['emailPlaceholder'] = "E-mailadres"
translations['nl']['passwordPlaceholder'] = "Wachtwoord"
translations['nl']['2faPlaceholder'] = "2FA code (Laat veld leeg indien uitgeschakeld)"
translations['nl']['loginInvalidInputs'] = "Onjuist e-mailadres en wachtwoord"
translations['nl']['alertOkButton'] = "Ok"
translations['nl']['loginWrongCrednltials'] = "Onjuist e-mailadres, wachtwoord of 2FA code"
translations['nl']['apiRequestError'] = "Er is een fout opgetreden met uw verzoek, probeer het later opnieuw"
translations['nl']['registerInvalidFields'] = "Ongeldige formuliervelden"
translations['nl']['registerPasswordAtLeast10Chars'] = "Uw wachtwoord moet minimaal 10 tekens lang zijn"
translations['nl']['registerPasswordsDoNotMatch'] = "Wachtwoorden komen niet overeen"
translations['nl']['registerInvalidEmail'] = "Ongeldig e-mailadres"
translations['nl']['registerEmailAlreadyRegistered'] = "Het opgegeven e-mailadres is al geregistreerd"
translations['nl']['registerCouldNotSnldEmail'] = "Ok"
translations['nl']['alertOkButton'] = "We konden op dit moment geen e-mail verzenden, probeer het later opnieuw"
translations['nl']['registerSuccess'] = "Uw account is aangemaakt, bevestig uw e-mailadres door op de link te klikken die we naar u hebben toegestuurd"
translations['nl']['registerInvalidInputs'] = "Ongeldig e-mailadres, wachtwoord en bevestig wachtwoord"

translations['sv']['close'] = "Stäng"
translations['sv']['cancel'] = "Avbryt"
translations['sv']['refresh'] = "Uppdatera"
translations['sv']['trashItem'] = "Papperskorg"
translations['sv']['moveItem'] = "Flytta"
translations['sv']['myCloud'] = "Mitt Cloud"
translations['sv']['loginTitle'] = "Logga in"
translations['sv']['registerTitle'] = "Skapa Konto"
translations['sv']['or'] = "eller"
translations['sv']['loginButton'] = "Logga in"
translations['sv']['registerButton'] = "Skapa Konto"
translations['sv']['registerLink'] = "Skapa Konto (Första 10 GB gratis)"
translations['sv']['loginLink'] = "Logga in"
translations['sv']['passwordRepeatPlaceholder'] = "Upprepa lösenord"
translations['sv']['emailPlaceholder'] = "E-postadress"
translations['sv']['passwordPlaceholder'] = "Lösenord"
translations['sv']['2faPlaceholder'] = "2FA kod (Fyll endast i om 2FA är aktiverat)"
translations['sv']['loginInvalidInputs'] = "Fel E-postadress eller lösenord"
translations['sv']['alertOkButton'] = "OK"
translations['sv']['loginWrongCredentials'] = "Fel E-postadress, lösenord eller 2FA kod"
translations['sv']['apiRequestError'] = "Request error, försök igen"
translations['sv']['registerInvalidFields'] = "Ogiltliga formulärfält"
translations['sv']['registerPasswordAtLeast10Chars'] = "Ditt lösenord måste vara längre än 10"
translations['sv']['registerPasswordsDoNotMatch'] = "Lösenorden matchar inte"
translations['sv']['registerInvalidEmail'] = "Ogiltlig E-postadress"
translations['sv']['registerEmailAlreadyRegistered'] = "Denna E-postadress används redan"
translations['sv']['registerCouldNotSendEmail'] = "OK"
translations['sv']['alertOkButton'] = "Kunde ej skicka verifieringsmail, försök igen senare"
translations['sv']['registerSuccess'] = "Kontot skapades, vänligen verifiera ditt konto genom att klicka på länken som du fick via epost"
translations['sv']['registerInvalidInputs'] = "Fel E-postadress, lösenord och upprepa lösenord"
translations['sv']['sharedWithMe'] = "Delat med mig"
translations['sv']['currentlySharing'] = "Delas av mig"
translations['sv']['settings'] = "Inställningar"
translations['sv']['encryption'] = "Kryptering"
translations['sv']['help'] = "Hjälp"
translations['sv']['trash'] = "Papperskorg"
translations['sv']['userStorageUsageMenuText'] = "__PERCENTAGE__% av __MAX__ använt"
translations['sv']['goProBadge'] = "Gå Pro"
translations['sv']['unknownDeviceError'] = "Ett okänt fel inträffade, starta om applikationen eller kontakta support"

translations[hin]['close'] = "बंद करे"
translations[hin]['cancel'] = "रद्द करे"
translations[hin]['refresh'] = "रिफ्रेश करे"
translations[hin]['trashItem'] = "ट्रैश"
translations[hin]['moveItem'] = "मूव"
translations[hin]['myCloud'] = "माई क्लाउड"
translations[hin]['loginTitle'] = "साइन इन करें"
translations[hin]['registerTitle'] = "खाता बनाएं"
translations[hin]['or'] = "या"
translations[hin]['loginButton'] = "साइन इन करें"
translations[hin]['registerButton'] = "खाता बनाएं"
translations[hin]['registerLink'] = "खाता बनाएं (पहले 10 GB मुफ्त)"
translations[hin]['loginLink'] = "साइन इन करें"
translations[hin]['passwordRepeatPlaceholder'] = "पुष्टि करे"
translations[hin]['emailPlaceholder'] = "ईमेल"
translations[hin]['passwordPlaceholder'] = "पासवर्ड"
translations[hin]['2faPlaceholder'] = "2FA कोड (नहीं है तो खाली छोड़े)"
translations[hin]['loginInvalidInputs'] = "ईमेल या पासवर्ड गलत है"
translations[hin]['alertOkButton'] = "ठीक है"
translations[hin]['loginWrongCredentials'] = "ईमेल, पासवर्ड या 2fa कोड गलत है"
translations[hin]['apiRequestError'] = "रिक्वेस्ट एरर, कृपया बाद में पुनः प्रयास करें"
translations[hin]['registerInvalidFields'] = "अमान्य फ़ार्म इनपुट"
translations[hin]['registerPasswordAtLeast10Chars'] = "आपका पासवर्ड कम से कम 10 वर्ण लंबा होना चाहिए"
translations[hin]['registerPasswordsDoNotMatch'] = "पासवर्ड मेल नहीं कर रहे"
translations[hin]['registerInvalidEmail'] = "अमान्य ईमेल पता"
translations[hin]['registerEmailAlreadyRegistered'] = "यह ईमेल पता पहले से पंजीकृत है"
translations[hin]['registerCouldNotSendEmail'] = "ठीक है"
translations[hin]['alertOkButton'] = "हम इस समय ईमेल नहीं भेज सके, कृपया बाद में पुनः प्रयास करें"
translations[hin]['registerSuccess'] = "खाता बन गया है, कृपया हमारे द्वारा भेजे गए लिंक पर क्लिक करके अपने ईमेल पते की पुष्टि करें"
translations[hin]['registerInvalidInputs'] = "ईमेल, पासवर्ड और पासवर्ड पुष्टि गलत है"
translations[hin]['sharedWithMe'] = "मेरे साथ शेयर्ड"
translations[hin]['currentlySharing'] = "वर्तमान में शेयरिंग"
translations[hin]['settings'] = "सेटिंग"
translations[hin]['encryption'] = "एन्क्रिप्शन"
translations[hin]['help'] = "सहायता"
translations[hin]['trash'] = "ट्रैश"
translations[hin]['userStorageUsageMenuText'] = "__MAX__ में से __PERCENTAGE__% का उपयोग किया गया है"
translations[hin]['goProBadge'] = "प्रो बने"
translations[hin]['unknownDeviceError'] = "आपके डिवाइस पर कोई अज्ञात त्रुटि आई है, एप्लिकेशन को पुनरारंभ करने का प्रयास करें या मदद के लिए हमारे सहयोग से संपर्क करें"
translations[hin]['uploadInvalidFileSize'] = "__NAME__ का अमान्य फ़ाइल साइज है"
translations[hin]['fileUploadFileAlreadyExists'] = "__NAME__ फ़ोल्डर में पहले से मौजूद है"
translations[hin]['fileUploadStarted'] = "__NAME__ अपलोड शुरू हो गया"
translations[hin]['fileUploadCouldNotReadFile'] = "__NAME__ पढ़ नहीं सका, अपलोड रद्द किया जा रहा है"
translations[hin]['couldNotImportKeys'] = "आपका कीपेयर आयात नहीं हो सका, कृपया पुनः प्रयास करें या सहयोग से संपर्क करें"
translations[hin]['fileUploadFailed'] = "__NAME__अपलोड नहीं हो सका, अपने इंटरनेट कनेक्शन की जाँच करें या सहयोग से संपर्क करें"
translations[hin]['fileUploadDone'] = "__NAME__ सफलतापूर्वक अपलोड हो गया है"
translations[hin]['fileUploadInvalidFileName'] = "__NAME__ एक अमान्य नाम है"
translations[hin]['alertOkButton'] = "ठीक है"

module.exports = {
    get: (lang = "en", text, firstUpperCase = true, replaceFrom = [], replaceTo = []) => {
        let gotText = translations[lang][text]

        if(!gotText){
            if(translations['en'][text]){
                return translations['en'][text]
            }

            return "NO_TRANSLATION_FOUND"
        }

        if(firstUpperCase){
            gotText = gotText.charAt(0).toUpperCase() + gotText.slice(1)
        }

        if(replaceFrom.length > 0 && replaceTo.length > 0){
            for(let i = 0; i < replaceFrom.length; i++){
                gotText = gotText.split(replaceFrom[i]).join(replaceTo[i])
            }
        }

        return gotText
    }
}
